HW7 is done
kirillgarbar/FirstSem pull request #10
Opened 2020-12-07 14:13 UTC by kirillgarbar

Выполнил все задания

2020-12-07 14:31 UTC, gsvgit requested changes

2020-12-07 14:31 UTC, gsvgit commented on src/HW7/MyList.fs
> +    match l with
Раз фолд написали, то длинк проще через него выразить.

2020-12-07 14:31 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW7.fs
> +        testProperty "fold test" <| fun a ->
А добавьте, пожалуйста, тесты, где будет видно, что свёртка в правильном поряжке происходит.

2020-12-07 14:44 UTC, kirillgarbar commented on tests/FirstSem.Tests/TestsHW7.fs
> +        testProperty "fold test" <| fun a ->
Чтобы убедиться в этом я генерирую список символов, которые потом сворачиваю двумя разными фолдами. Равенством получившихся строк обеспечивается правильный порядок свёртки

2020-12-08 05:49 UTC, gsvgit approved these changes

2020-12-08 08:16 UTC, merged