HW8 Long arithmetics
kirillgarbar/FirstSem pull request #11
Opened 2021-02-05 23:42 UTC by kirillgarbar

Некоторые вспомогательные функции дописал в модуль MyList из седьмой домашки

2021-02-06 08:01 UTC, gsvgit requested changes

2021-02-06 08:01 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    val Bits:MyList<int>
Точно биты? Может всё же цифры?

2021-02-06 08:01 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    val Sign:int
Знак --- это int? Заведите тип со всего двумя соответствующими значениями.

2021-02-06 08:01 UTC, gsvgit commented on src/HW7/MyList.fs
> +let rec delZeroHead l = // удаляет все нули из префикса списка
Думается, тут слишком много функций, которые специфичны именно для арифметики, а значит не должны быть в списке. Должны быть где-то в другом месте.

2021-02-06 08:01 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    else
есть ```elif```

2021-02-06 08:01 UTC, gsvgit commented on src/HW8/BigInt.fs
> +        if y.Bits = One 0 then failwith "Division by zero"
Лучше либо всё в одну строку, либо тогда всё в столбик
```
if ...
then ...
else ...
```

2021-02-06 08:01 UTC, gsvgit commented on src/HW7/MyList.fs
> +let intToMyList i =
В F#  есть своя длинная арифметика (BigInt). Лучше сразу с ней дружить, наверное. Для тестов точно лучше.

2021-02-06 08:01 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW8.fs
> +    let y = x |> string
А, вот они, конвертеры. Ок.

2021-02-06 08:01 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW8.fs
> +    if x.Sign <> y.Sign
Казалось бы, равенство --- достаточно полезная функция. Почему она только в тестах?

2021-02-06 08:01 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW8.fs
> +        | One y1 -> if x1 = y1 then true else false
Вот за такие ```if```-ы убивать надо.

2021-02-08 06:57 UTC, gsvgit requested changes

2021-02-08 06:57 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    val Numbers:MyList<int>
Digits. Numbers --- это немного другое. Думаю, примерно как цифры и числа в русском.

2021-02-08 06:57 UTC, gsvgit commented on src/HW8/BigInt.fs
> +            if (fold (fun _ i -> if (i < 0 || i > 9) then false else true) true b)
```if cond then Bool else Bool``` --- это зло какое-то. Не надо так.

2021-02-08 06:57 UTC, gsvgit commented on src/HW8/BigInt.fs
> +let rec equal (x:BigInt) (y:BigInt) =
Что-то мне подсказывает, что сам equal не должен быть рекурсивным. Сперва вы один раз сравниваете знаки, а потом, внутри, рекурсивно "тела". И то, мне кажется что можно ещё длину сравнить. Опять же, у Вас map2 есть. Сравнение замечательно через него выражается.

2021-02-08 06:57 UTC, gsvgit commented on src/HW8/BigInt.fs
> +let notLesser x y = // сравнивает списки в лексикографическом порядке
А правда, почему у Вас не просто  compare, который возвращает одно из трёх значений (больше, равно, меньше)?

2021-02-08 06:57 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    if x.Sign = y.Sign                  // Поэтому приходится делать проверку на модуль и знак
Кажется, через match здесь было бы короче:
```
match (x.Sign,y.Sign) with
| (Positive, Positive) -> ...
| ....
```

2021-02-08 06:57 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    let rec go x y r rank =
Много дублирования кода. И кажется, Вы тут ещё раз руками фолды-мапы понаписали.

2021-02-09 04:11 UTC, kirillgarbar commented
Есть ещё такой вариант equal, но в нём мы в любом случае производим поразрядное сравнение, так что ради экономии времени выбрал тот, что в коммите
![image](https://user-images.githubusercontent.com/71129570/107314589-01aa8580-6aa6-11eb-843f-1c7d9253a19a.png)

2021-02-09 05:38 UTC, gsvgit requested changes
Уже почти хорошо. Деление, правда, диковато выглядит, но у меня у самого оно так себе. Не уверен, что знаю, как его прям красиво написать)

2021-02-09 05:38 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    if x.Sign <> y.Sign || len x.Digits <> len y.Digits
1) Мне всё ещё кажется, что зря Вы такие случаи, когда выражение однострочное, 
 оформляете так, а не записывая его на той же строке, что и ключевое слово. Типа такого:
```
if x.Sign <> y.Sign || len x.Digits <> len y.Digits
then false
else map2 (fun x y -> x = y) x.Digits y.Digits |> fold (fun c x -> c && x) true
```
2) Отдельный разговор, что любые if-ы с булевым результатом переписываются в виде простого булева вырожения. Но тут, вероятнро, if красивее выглядит.

2021-02-09 05:38 UTC, gsvgit commented on src/HW8/BigInt.fs
> +        map2 (fun x y -> x = y) x.Digits y.Digits |> fold (fun c x -> c && x) true
Правда ли, что тут не просто ```fold (&&) true``` ?

2021-02-09 05:38 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
Гы-гы. То есть 0 передать всё же можно, но ожидается только 1 или -1.

2021-02-09 05:44 UTC, kirillgarbar commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
Сделал так только потому, что sign из стандартной библиотеки возвращает 0, если ему дать 0, а мне хочется, чтоб знак или Positive или Negative был)

2021-02-09 05:47 UTC, kirillgarbar commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
Могу функцию sign для этого модуля переписать так, чтоб 1 или -1 возвращала, но как-то странно это будет по-моему

2021-02-09 05:47 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
Ок. Вот это как раз место, где комментарии не помешали бы. потому что из кода как раз не совсем понятно, что это не косяк какой-то.

2021-02-09 05:48 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
Комментарий, поясняющий, почему именно так, точно добавть стоит. А переписывать, может, и не надо.

2021-02-09 05:49 UTC, kirillgarbar commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
А, туплю. Можно же просто описание ошибки поправить)))

2021-02-09 05:53 UTC, gsvgit commented on src/HW8/BigInt.fs
> +            if notLesser x f.Digits
И да. Проблему с форматированием ```if``` надо по всему коду поправить)

2021-02-09 05:54 UTC, gsvgit commented on src/HW8/BigInt.fs
> +    if x = 1 || x = 0 then Positive elif x = -1 then Negative else failwith "1 or -1 expected"
Ну вообще да. Тоже вариант)

2021-02-09 05:57 UTC, kirillgarbar commented on src/HW8/BigInt.fs
> +            if notLesser x f.Digits
![image](https://user-images.githubusercontent.com/71129570/107322054-c3689280-6ab4-11eb-873b-9b4dd115f5d6.png)
В таком случае, я полагаю, всё впорядке с форматированием?

2021-02-09 06:04 UTC, gsvgit commented on src/HW8/BigInt.fs
> +            if notLesser x f.Digits
На последней строке всё норм: короткий if, всё в одну строку. 

Третью строку я бы поднял.
```
if lx <> ly
then lx > ly
else 
   let ...
```

То же самое можно делать и если под else что-то короткое, а then большой-разлапистый.

```
if lx <> ly
then 
   ...
   ...
else f x y
```

2021-02-09 06:31 UTC, gsvgit approved these changes
Ок.

2021-02-09 06:31 UTC, gsvgit commented on src/HW8/BigInt.fs
> +            else failwith "Numbers should be in range 0..9"
Всё таки Digits.

2021-02-09 06:34 UTC, merged

2021-02-09 06:36 UTC, gsvgit commented
Что ж, поздравляю. Теперь можно интерпретатор писать)