RuFS
kirillgarbar/FirstSem pull request #13
Opened 2021-03-14 15:19 UTC by kirillgarbar

В тестах всё-таки решил использовать Expecto для вычисления значения выражений. В файле с тестами также принтится результат компиляции некоторого кода и ожидаемый результат для проверки корректности вывода в консоль.

2021-03-16 11:23 UTC, gsvgit requested changes

2021-03-16 11:23 UTC, gsvgit commented on src/RuFS/AST.fs
> +    | Num of string
А почему не сразу нормальное число, а строка?

2021-03-16 11:23 UTC, gsvgit commented on src/RuFS/Interpreter.fs
> +        | _ -> failwithf "Variable %A is not declared." nv
Не очень честно. мало ли из-за чего интерпретатор упал. Не обязательно из-за необъявленной переменной.

2021-03-16 11:23 UTC, gsvgit commented on src/RuFS/Lexer.fsl
> +let number = ( '+' | '-' )? + [ '0'-'9' ]*
То есть числа бывают пустыми? Из нуля цифр.

2021-03-16 11:23 UTC, gsvgit commented on src/RuFS/Lexer.fsl
> +let vname = '[' [ 'a'-'z' 'A'-'z' ]* ']'
Гы-гы. А зачем Вы скопитырили квадратные скобки. Я обхяснял, откуда они у меня взялись. А у Вас откуда?

2021-03-16 11:23 UTC, gsvgit commented on src/RuFS/Main.fs
> +    | p when p.Contains(Input) ->
А чем input  от calculate отличается? Наш же язык как раз вычисляет. И ещё. могу ли я запустить интерпрететатор, чтобы он отработал "как обычно", но ещё нарисовал дерево?

2021-03-16 11:23 UTC, gsvgit commented on src/RuFS/RuFS.fsproj
> +      <None Include="Parser.fsy" />
Так. А как Вы fs-файлы получаете? Почему это не часть сборки?

2021-03-16 11:23 UTC, gsvgit commented on tests/FirstSem.Tests/TestRuFS.fs
> +            let bp = "let [x] = 5 + 2 * ((4 - 2) - 7 / (3 * 2))"
А почему нету каких-нибудь делений на 0, чисел со знаками (Ваш лексер их допускает).

2021-03-16 12:59 UTC, kirillgarbar commented on src/RuFS/Main.fs
> +    | p when p.Contains(Input) ->
![image](https://user-images.githubusercontent.com/71129570/111312520-6d1cdf80-8670-11eb-964f-cdfc1169e33c.png)
![image](https://user-images.githubusercontent.com/71129570/111312544-73ab5700-8670-11eb-8f5b-8b47aad6819d.png)
У нас в задании написана возможность задавать выражение в консоль(calculate) и путь к файлу с кодом(input), поэтому реализовал оба варианта

2021-03-16 13:07 UTC, gsvgit commented on src/RuFS/Main.fs
> +    | p when p.Contains(Input) ->
Да, отлично. А теперь смотрите. Я хочу, чтобы 
1) выражение просто посчиталось
2) Наприсовалось дерево разбора выражения
3) Выраение почиталось и нарисовалось дерево разбра.

2021-03-19 07:04 UTC, gsvgit requested changes

2021-03-19 07:04 UTC, gsvgit commented on src/RuFS/Main.fs
> +[<EntryPoint>]
Жесть. Сразу видно, что с командной строкой Вы ещё не подружились. Зачем делать руками прямое произведение всех опций, если можно сделать просто отдельные ключи. Отдельно указываем какой вход, отдельно, если надо вычислять, отдельно, надо ли рисовать DOT.

2021-03-19 07:04 UTC, gsvgit commented on src/RuFS/Parser.fsy
> +%token <string> NUM
Всё ещё строка. Но почему?

2021-03-19 07:04 UTC, gsvgit commented on tests/FirstSem.Tests/TestRuFS.fs
> +    let [y] = 7
Всё ещё квадратные скобки. А в лексере их нету. А всё потому, что генерацию руками запускаете. Наверняка забыли перегенерировать файлы просто.

2021-03-19 07:04 UTC, gsvgit commented on tests/FirstSem.Tests/TestRuFS.fs
> +    print [x]
А ещё Ваш лексер допускает числа вида ```-00001``` или даже просто ```-000000```. Что-то не уверен, что таоке в интерпретаторе всегда корректно обрабатывается.

2021-03-19 14:48 UTC, kirillgarbar commented on tests/FirstSem.Tests/TestRuFS.fs
> +    print [x]
При появлении таких чисел следует выводить ошибку или убирать незначащие нули? Мне второй вариант более логичным кажется

2021-03-19 15:30 UTC, kirillgarbar commented on src/RuFS/Main.fs
> +[<EntryPoint>]
![image](https://user-images.githubusercontent.com/71129570/111804361-0fdb9500-88e1-11eb-8a39-740ed3f73d87.png)
Это имелось ввиду?

2021-03-19 15:39 UTC, gsvgit commented on src/RuFS/Main.fs
> +[<EntryPoint>]
Примерно. Разве что файл сперва прочитать надо, потом парсить.

2021-03-22 07:33 UTC, gsvgit requested changes
Буквально над парой моментов осталось подумать.

2021-03-22 07:33 UTC, gsvgit commented on src/HW8/BigInt.fs
> +        | _ -> go (mul r n) (sub p (BigInt(Positive, One 1)))
А почему бы не применить трюк, который использовали для матриц, и не ускорить возведение в сепень?

2021-03-22 07:33 UTC, gsvgit commented on src/RuFS/Lexer.fsl
> +let wrongNumber = sign + '0' + [ '0'-'9' ]+
Что?) Как Вы думаете, в реальных анализаторах все вохможные некорректные случаи явно руками перечисляют? Кажется, некорректный ввод должен более естественным путём приводить к ошибке.

2021-03-23 06:25 UTC, gsvgit approved these changes

2021-03-23 06:25 UTC, gsvgit commented on src/RuFS/Lexer.fsl
> +let number = sign + ('0' ' ' | digits)
Ну, такое себе решение. Но да пусть пока будет.

2021-03-23 08:38 UTC, merged