Best IDE ever
kirillgarbar/FirstSem pull request #14
Opened 2021-05-21 20:35 UTC by kirillgarbar

Сделаны задания 2 3 4, то есть всё кроме условных операторов. Чтобы пакет качался на локалке, добавил переменную окружения NUGET_AUTH_TOKEN со своим токеном для авторизации(она используется в build.cmd, build.sh и в нюгет конфиге, лежащем в JBKiller)

2021-05-26 12:53 UTC, gsvgit commented
Запускаем IDE. В открывшемся окне набираем следующее:
```
x = 12
y = 2323232323232399999999999999999
z = y ^ x
print z

y = z / 5
y = # y
print y
```

Ставим галочку "Debug", ставим точку остановки на строке 6 (y = z / 5), говорим "Run", в консоли:
```
Length cannot be less than zero. (Parameter 'length')
```

2021-05-26 12:55 UTC, gsvgit commented
А ещё мне чертовски интересно, почему я не могу ресайзить основное окно и консоль.

2021-05-26 12:56 UTC, gsvgit commented
А ещё у Вас IDE зависает пока считает. Не дело это.

2021-05-26 13:09 UTC, gsvgit commented
Огонь! Жмём "Load file", открывается системный проводник, жмём Esc, закрывается всё, вместе с IDE, хотя должен только проводник.

2021-05-30 11:48 UTC, kirillgarbar commented
Баг с пустой строкой так и не удалось воспроизвести, но место, где он скорее всего возникает, я поправил

2021-06-01 07:22 UTC, gsvgit commented
Запускаем IDE, пишем
```
x = 5

y = x + 2

print x
```

Ставим точку остановки на 3 строку, ставим галочку Debug, нажимаем Run, IDE закрывается с сообщением 
```
Unhandled exception. System.AggregateException: One or more errors occurred. (parse error)
 ---> System.Exception: parse error
   at FSharp.Text.Parsing.Implementation.popStackUntilErrorShifted@303[tok,a](Tables`1 tables, LexBuffer`1 lexbuf, Stack`1 stateStack, Stack`1 valueStack, AssocTable actionTable, FSharpOption`1 tokenOpt)
   at FSharp.Text.Parsing.Implementation.interpret[tok,a](Tables`1 tables, FSharpFunc`2 lexer, LexBuffer`1 lexbuf, Int32 initialState)
   at CalculatorFSharp.Main.parse(String text)
   at AvaloniaEditDemo.Views.MainWindow.<>c__DisplayClass9_0.<RunB_Click>b__3() in /home/gsv/Projects/IDEs_2sem_2021/Garbar/FirstSem/src/JBKiller/Views/MainWindow.axaml.cs:line 103
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AvaloniaEditDemo.Views.MainWindow.<>c__DisplayClass9_1.<RunB_Click>b__5() in /home/gsv/Projects/IDEs_2sem_2021/Garbar/FirstSem/src/JBKiller/Views/MainWindow.axaml.cs:line 110
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaEditDemo.Program.Main(String[] args) in /home/gsv/Projects/IDEs_2sem_2021/Garbar/FirstSem/src/JBKiller/Program.cs:line 13
Aborted (core dumped)
```

2021-06-01 09:29 UTC, kirillgarbar commented
У меня опять баг не воспроизводится)
![image](https://user-images.githubusercontent.com/71129570/120300892-07d2a500-c2d5-11eb-9eef-fa3e1b35c84c.png)

2021-06-03 20:36 UTC, KostinP commented
Cool user interface!!
![image](https://user-images.githubusercontent.com/50001467/120708570-6611aa80-c4c4-11eb-84b6-68da1cea4943.png)

> У меня опять баг не воспроизводится)
> ![image](https://user-images.githubusercontent.com/71129570/120300892-07d2a500-c2d5-11eb-9eef-fa3e1b35c84c.png)

2021-08-01 16:43 UTC, kirillgarbar commented
Падений на дебаге в линуксе при наличии пустых строк быть не должно, консоль теперь ресайзится, а при загрузке файла его путь запоминается для его сохранения. Дебаг теперь работает по-другому: при нажатии на Run с галочкой на отладке, кнопка Run становится кнопкой Continue, код и кнопки остановок становятся недоступны для редактирования пока отладка не прекратится по нажатию Stop, завершению отладки или возникновению ошибки. Текущая точка остановки теперь подсвечивается синим.

2021-08-06 08:08 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                    else if (startOfDebug)
# :hankey: #

2021-08-06 08:44 UTC, kirillgarbar commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                    else if (startOfDebug)
![image](https://user-images.githubusercontent.com/71129570/128483391-83fb51f4-d351-4c38-82f2-02a640113bf9.png)
Так сойдёт?

2021-08-20 05:59 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                    else if (startOfDebug)
"и так сойдёт..."

2021-08-20 06:08 UTC, gsvgit requested changes

2021-08-20 06:08 UTC, gsvgit commented on src/JBKiller/ArithmHighlighting.xshd
> +            \b0[xX][0-9a-fA-F]+  # hex number
А Вы таке числа поддерживаете?

2021-08-20 06:08 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +            foreach (string key in d.Keys) res += key + " = " + d[key] + "\n";
Выглядит как... :hankey:

2021-08-20 06:08 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                foreach (string s in arr) if (s.Length > 0) res += s + " ";
Неужели ещё не придумали нормальный string.concat или что-нибудь подобное?

2021-08-20 06:08 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                for (int i = 0; i < bpIndices.Length; i++) result.Enqueue(arrayToString(lines[0..bpIndices[i]]));
Гы-гы. То есть Вы кажлый раз исполняете всё от самого начала? А если там каждая инструкция по часу счиатется?

2021-08-20 06:08 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                        return DictToString(d.Item2);
Что за Item2 ?

2021-08-20 06:08 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                    return d.Item3["print"];
Ммм...

2021-08-23 07:20 UTC, gsvgit reviewed
Уже почти победа.

2021-08-23 07:20 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                    else if (startOfDebug)
Что-то, кажется, так и не поправили.

2021-08-23 07:20 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                        return Interpreter.runVariables(new(variablesDict, intepreterDict), Main.parse(currentSlice));
Прикольный вариант. Альтернатива --- скармливать интерпретатору весь код разом, просто уметь останавливать его в нужных места и продолжать интерпретацию после остановки.

Можете раасказть плюсы и минусы Вашего решения по сравнению с альтернативным?

2021-08-23 07:47 UTC, kirillgarbar commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                        return Interpreter.runVariables(new(variablesDict, intepreterDict), Main.parse(currentSlice));
Минусы - надо нарезать код на куски и играться со словарями
Плюс - простота реализации :)

Сложно представить, как такое можно реализовать без капитального переосмысления работы интерпретатора. Первое, что пришло в голову - парсить код целиком и нарезать уже список стейтментов на куски, но кроме сэкономленной памяти на хранение кода это ничего не даст, так ещё и не ясно как сопоставить друг другу список стейтментов и брейкпоинты, чтобы разбить код.

2021-08-23 08:11 UTC, gsvgit commented on src/JBKiller/Views/MainWindow.axaml.cs
> +                        return Interpreter.runVariables(new(variablesDict, intepreterDict), Main.parse(currentSlice));
Ещё при Вашей реализации код можн опо ходу дела менять. А вот плюс это или минус --- зависит от ситуации.

2021-08-23 10:43 UTC, gsvgit commented
Открываю IDE, пишу код
```
x  = 10
```
Нажимаю Run, ничего не происходит.

2021-08-24 06:38 UTC, gsvgit commented
1) Блокировать возможность ставить новые точки остановки --- не вариант. Это вполне нормальный сценарий: по ходу отладки понять, что нужно ещё где-нибудь остановиться.

2) Почему на последней строке нет живых пременных? Казалось бы...
![Screenshot from 2021-08-24 09-20-32](https://user-images.githubusercontent.com/106816/130566613-565d12e4-9d2f-4cad-8a60-a74ef4f7cac8.png)

3) 
```
Interpretation is finished!
200
2000

```
Почему у Вас сперва заканчивается интерпретация, а потом появляются результаты?

Вообще, проблема даже более глобальная. У Вас интерфейс неадекватно реагирует на действия пользователя. Если написать программу, которая долго интрпретируется и нажать run, то ничего не происходит. Не понятно, всё сломалось, реально ничего не произошло, если произошло, то что. Пользователь должен явно видеть, что происходит в ответ на его действия.

Как Вы думаете, что сейчас происходит?
![Screenshot from 2021-08-24 09-33-13](https://user-images.githubusercontent.com/106816/130567813-00ad731c-1fc3-4eba-96ca-e68c571361ff.png)

4) Что, простите? В документации написано, что это возведение в степень.
![Screenshot from 2021-08-24 09-35-59](https://user-images.githubusercontent.com/106816/130568170-5094d441-e154-4216-9c34-9e2ed91278cc.png)

5) Запускаем IDE, жмём LoadFile, выбираем какую-нибудь dll (напермиер, System-что-нибудь из результатов компиляции), приложение зависает.

2021-09-01 22:03 UTC, kirillgarbar commented
Все пункты ревью пофиксил, код и точки остановки теперь динамические, добавил предупреждение в консоль, когда код, добавляемый пользователем выше текущей точки, не выполнится. Номер строки, на которой появляется синяя точка, запоминается, и шаг отладки происходит с этой строки до строки с ближайшей красной точкой

2021-09-02 06:55 UTC, gsvgit commented
Запускаю IDE, нажимаю Load file, ничего не делаю и сразу нажимаю на клавиатуре Esc. IDE падает:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at JBKiller.Views.MainWindow.LoadB_Click(Object sender, RoutedEventArgs e) in /home/gsv/Projects/IDEs_2sem_2021/Garbar/FirstSem/src/JBKiller/Views/MainWindow.axaml.cs:line 211
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at JBKiller.Program.Main(String[] args) in /home/gsv/Projects/IDEs_2sem_2021/Garbar/FirstSem/src/JBKiller/Program.cs:line 13
Aborted (core dumped)
```

2021-09-02 08:44 UTC, kirillgarbar commented
На винде такого не возникает, добавил ещё одну проверку

2021-09-02 18:49 UTC, kirillgarbar commented
Теперь если код изменён во время вычисления, в консоль выводится предупреждение

2021-09-03 06:45 UTC, gsvgit approved these changes
Вполне прилично. Для первого раза пойдёт)

2021-09-15 23:13 UTC, merged