Generator is done
kirillgarbar/FirstSem pull request #15
Opened 2021-08-02 16:40 UTC by kirillgarbar

Сделал консольный генератор матриц. Требуется указать количество строк и столбцов, процент нулевых(нейтральных) элементов, тип данных и путь к папке, в которую нужно выложить матрицы

2021-08-20 05:58 UTC, gsvgit requested changes

2021-08-20 05:58 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +    let matrixToString (a:string [][]) = Array.fold (fun s i -> s + (Array.fold (fun s1 j -> s1 + j + " ") "" i).Trim() + "\n") "" a
Если что, есть String.concat

2021-08-20 05:58 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +    let writeMatrix path (m:string [][]) = IO.File.WriteAllText(path, matrixToString m)
А теперь гененрируем матрицу 10^6 на 10^6. Точно вся строка в оперативку влезет?

2021-08-20 05:58 UTC, gsvgit commented on src/MatrixGenerator/Main.fs
> +            let generator = if p.Contains(Int) then intGenerator elif p.Contains(Bool) then boolGenerator elif p.Contains(Float) then floatGenerator else failwith "You must enter a type"
Хе-хе. Вообще, у вас сейчас Int, Bool, Float --- независимые ключи и я могу указать все три сразу. Почему обработается только один из них?

2021-08-20 05:58 UTC, gsvgit commented on tests/FirstSem.Tests/MatrixGeneratorTest.fs
> +       let im = generateMatrix (Random().Next(1, 10)) (Random().Next(1, 10)) (Random().Next(101)) intGenerator
Но зачем всё в один тест мешать?

2021-08-20 10:49 UTC, kirillgarbar commented on src/MatrixGenerator/Generator.fs
> +    let writeMatrix path (m:string [][]) = IO.File.WriteAllText(path, matrixToString m)
Даже если этот момент оптимизировать, бутылочным горлышком будет являться генерация матрицы таких размеров

2021-08-20 10:54 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +    let writeMatrix path (m:string [][]) = IO.File.WriteAllText(path, matrixToString m)
Ну как сказать. Если Вы её таки сгенерируете, а потом несможете в файл записать, то будет досадно. Ну и следующий вопрос: можно ли сделать генерацию матрицы лучше?

2021-08-20 12:03 UTC, kirillgarbar commented on src/MatrixGenerator/Generator.fs
> +    let writeMatrix path (m:string [][]) = IO.File.WriteAllText(path, matrixToString m)
Тогда полагаю, что такой способ записи должен решить проблему с оперативкой
![image](https://user-images.githubusercontent.com/71129570/130230035-97664563-5cfb-45c9-9132-225e4b2e4d08.png)

2021-08-20 12:14 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +    let writeMatrix path (m:string [][]) = IO.File.WriteAllText(path, matrixToString m)
Хорошая попытка, но можно проще: https://docs.microsoft.com/ru-ru/dotnet/api/system.io.file.writealllines?view=net-5.0#System_IO_File_WriteAllLines_System_String_System_Collections_Generic_IEnumerable_System_String__System_Text_Encoding_

2021-08-20 12:39 UTC, gsvgit requested changes
С коллекциями надо разобраться. В остальном нормально.

2021-08-20 12:39 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
И кому я про seq и array рассказывал. Ерунда тут у Вас получилась.

2021-08-20 12:51 UTC, kirillgarbar commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
Как-то не ясно в чём тут беда, можно без мапа обойтись было?

2021-08-20 12:59 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
Вы от исходной проблемы не избавились.  Все строки всё равно будут в памяти сперва.

2021-08-20 13:22 UTC, kirillgarbar commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
Тогда непонятно как WriteAllLines использовать, ведь оно требует, чтобы был какой-то массив строк

2021-08-20 13:27 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
Ооо.... Вы ещё и до конца прочитать не можете(

2021-08-20 13:53 UTC, kirillgarbar commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
Посмотрев примеры по той ссылке, увидел разве что то, что можно как-то так сделать, не создавая writer
![image](https://user-images.githubusercontent.com/71129570/130243098-3cead210-7c3e-4bac-9ee2-550f0e2d5df2.png)

2021-08-20 14:04 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
То есть про Seq Вы не знаете. Жаль. Зачёт ставить рановато.

2021-08-20 14:15 UTC, kirillgarbar commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
Может тогда хотя бы намекнёте каким образом здесь можно выиграть от использования Seq?

2021-08-20 14:35 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +        let writeArray = Array.map (String.concat " ") m
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences  В первом же абзаце есть основная идея.

2021-09-08 19:43 UTC, kirillgarbar commented
Вместо массивов теперь используется seq. Из-за рандома в формуле матрицы в id тестах перехожу обратно к массивам, чтобы считывалось действительно то же, что было записано

2021-09-13 08:40 UTC, gsvgit requested changes

2021-09-13 08:40 UTC, gsvgit commented on tests/FirstSem.Tests/MatrixGeneratorTest.fs
> +       let im = generateMatrix (Random().Next(1, 10)) (Random().Next(1, 10)) (Random().Next(101)) Int |> Array.ofSeq |> Array.map (Array.ofSeq)
А зачем Вам здесь рандом, если у Вас есть и так поставщик случайных данных?

2021-09-13 08:40 UTC, gsvgit commented on tests/FirstSem.Tests/MatrixGeneratorTest.fs
> +       let im = generateMatrix (Random().Next(1, 10)) (Random().Next(1, 10)) (Random().Next(101)) Int |> Array.ofSeq |> Array.map (Array.ofSeq)
Ну и про остальные тесты тот же вопрос.

2021-09-13 13:17 UTC, gsvgit approved these changes
Вполне прилично.

2021-09-13 13:28 UTC, merged