Home Work 2
kirillgarbar/FirstSem pull request #2
Opened 2020-09-23 14:57 UTC by kirillgarbar

Выполнил все домашние задания в виде функций(HW2,fs), написал и провёл тесты к ним(Tests HW2.fs), реализовал чтение и ввод через консоль (Main.fs)

2020-09-23 15:35 UTC, gsvgit requested changes

2020-09-23 15:35 UTC, gsvgit commented on src/FirstSem/HW2.fs
> +    a.[i] <- a.[i] + a.[j]
Вы делаете слишком сильное предположение о том, что индексы всегда в нужном диапазоне. Вообще, Вам этого никто не гарантирует.

2020-09-23 15:35 UTC, gsvgit commented on src/FirstSem/HW2.fs
> +        if a.[i] < x then r <- r + i.ToString() + " "
Хорошо. А можно всё таки найти индексы, а не строчку?

2020-09-23 15:35 UTC, gsvgit commented on README.md
> -
А как так получается, что у Вас части первой домашки попадают во вторую?

2020-09-23 17:34 UTC, kirillgarbar commented on README.md
> -
Сперва выполнил первое дз отредачив readme через гитхаб и не загрузил его в локальный репозиторий, поэтому заменил локальный readme на тот что был в гитхабе и снова его отправил на гитхаб

2020-09-24 06:28 UTC, gsvgit commented on README.md
> -
Ну вот в следующий раз внимательнее. Нужно чтобы в реквесте было только то, что относится к домашке.

2020-09-24 06:36 UTC, gsvgit requested changes

2020-09-24 06:36 UTC, gsvgit commented on tests/FirstSem.Tests/Tests.fs
А зачем Вам какой-то пустой файл?

2020-09-24 06:36 UTC, gsvgit commented on tests/FirstSem.Tests/Tests HW2.fs
> +            Expect.equal [| 1; 4; 3; 2; 5 |] (HW2.swapTwoByIndex(1, 3, [| 1; 2; 3; 4; 5 |])) "Resulting array should be [| 1; 4; 3; 2; 5 |]"
Есть вещи типа ```Expect.throwsT```, которые позволяют проверять, что кидается ровно то исключение, которое Вы планировали. Так что можно все поведения проверить.

2020-09-24 06:36 UTC, gsvgit commented on src/FirstSem/Main.fs
> +                | CalculateNaively _ -> "Calculates X^4+x^3+x^2+x^1+1 (Task 1)"
А почему часть иксов большие, а часть маленькие?

2020-09-24 15:15 UTC, kirillgarbar commented on tests/FirstSem.Tests/Tests HW2.fs
> +            Expect.equal [| 1; 4; 3; 2; 5 |] (HW2.swapTwoByIndex(1, 3, [| 1; 2; 3; 4; 5 |])) "Resulting array should be [| 1; 4; 3; 2; 5 |]"
Если я исправлю все эти недочёты и не добавлю новых то работа будет зачтена? Больше ничего исправлять не нужно?

2020-09-24 15:40 UTC, gsvgit commented on tests/FirstSem.Tests/Tests HW2.fs
> +            Expect.equal [| 1; 4; 3; 2; 5 |] (HW2.swapTwoByIndex(1, 3, [| 1; 2; 3; 4; 5 |])) "Resulting array should be [| 1; 4; 3; 2; 5 |]"
Да, вроде, всё остальное прилично выглядит.

2020-09-24 17:22 UTC, kirillgarbar commented on tests/FirstSem.Tests/Tests HW2.fs
> +            Expect.equal [| 1; 4; 3; 2; 5 |] (HW2.swapTwoByIndex(1, 3, [| 1; 2; 3; 4; 5 |])) "Resulting array should be [| 1; 4; 3; 2; 5 |]"
У меня функция возвращает неизменённый массив если возникает исключение, сгодится ли если я просто напишу тест через Expect.equal, проверяющее, что массив остался неизменным?
Чтобы применить Expect.throwsT потребуется переписать обработку исключений в функции через failwith(потому что тогда не требуется вывести массив как результат функции), что вроде как убивает сам смысл обработки этого исключения
![image](https://user-images.githubusercontent.com/71129570/94176883-666f9580-fea1-11ea-90c3-5b4b1a9072ac.png)

2020-09-24 17:42 UTC, gsvgit commented
Ладно, пока пойдет.

On Thu, Sep 24, 2020, 8:23 PM kirillgarbar <notifications@github.com> wrote:

> *@kirillgarbar* commented on this pull request.
> ------------------------------
>
> In tests/FirstSem.Tests/Tests HW2.fs
> <https://github.com/kirillgarbar/FirstSem/pull/2#discussion_r494486489>:
>
> > +            Expect.equal [| -2; -1 |] (HW2.swapFS([| -1; -2 |])) "Resulting array should be [| -2; -1 |]"
>
> +        testCase "Taks 5.4 Both elements are negative but first is greater by absolute value" <| fun _ ->
>
> +            Expect.equal [| -1; -2 |] (HW2.swapFS([| -2; -1 |])) "Resulting array should be [| -1; -2 |]"
>
> +        testCase "Taks 5.5 First is negative, second is positive and greater by absolute value" <| fun _ ->
>
> +            Expect.equal [| 2; -1 |] (HW2.swapFS([| -1; 2 |])) "Resulting array should be [| 2; -1 |]"
>
> +        testCase "Taks 5.6 First is negative, second is positive and lesser by absolute value" <| fun _ ->
>
> +            Expect.equal [| 1; -2 |] (HW2.swapFS([| -2; 1 |])) "Resulting array should be [| 1; -2 |]"
>
> +        testCase "Taks 5.7 First is positive, second is negative and greater by absolute value" <| fun _ ->
>
> +            Expect.equal [| -2; 1 |] (HW2.swapFS([| 1; -2 |])) "Resulting array should be [| -2; 1 |]"
>
> +        testCase "Taks 5.8 First is positive, second is negative and lesser by absolute value" <| fun _ ->
>
> +            Expect.equal [| -1; 2 |] (HW2.swapFS([| 2; -1 |])) "Resulting array should be [| -1; 2 |]"
>
> +
>
> +        // swap alrgorithm has already been tested, so it won't be tested for task 6
>
> +
>
> +        testCase "Taks 6.1 i is lesser then j" <| fun _ ->
>
> +            Expect.equal [| 1; 4; 3; 2; 5 |] (HW2.swapTwoByIndex(1, 3, [| 1; 2; 3; 4; 5 |])) "Resulting array should be [| 1; 4; 3; 2; 5 |]"
>
>
> У меня функция возвращает неизменённый массив если возникает исключение,
> сгодится ли если я просто напишу тест через Expect.equal, проверяющее, что
> массив остался неизменным?
> Чтобы применить Expect.throwsT потребуется переписать обработку исключений
> в функции через failwith(потому что тогда не требуется вывести массив как
> результат функции), что вроде как убивает сам смысл обработки этого
> исключения
> [image: image]
> <https://user-images.githubusercontent.com/71129570/94176883-666f9580-fea1-11ea-90c3-5b4b1a9072ac.png>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/kirillgarbar/FirstSem/pull/2#discussion_r494486489>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQGG4DDTW4G2MJ7K7JDSHN57ZANCNFSM4RXETNYA>
> .
>

2020-09-24 19:05 UTC, merged