HW3 is done
kirillgarbar/FirstSem pull request #6
Opened 2020-10-02 19:51 UTC by kirillgarbar

Выполнил все задания

2020-10-03 18:29 UTC, gsvgit requested changes

2020-10-03 18:29 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +    if a.Length = 0 || a.[0].Length = 0
А правда, что эта проверка нужна? Кажется, функция умножения сама проверит.

2020-10-03 18:29 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +        for i = 2 to p do
Кажется, Вы потеряли нулевую степень. Я про единичную матрицу не просто так рассказывал. И, кстати, не проверили показатель на корректность.

2020-10-03 18:29 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +        for i = 2 to n do
А почему здесь не просто степеь матрицы?

2020-10-03 18:29 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +        let rec go n =
Чот сложно. Может проще написать две разных функции возведения в сепень?

2020-10-03 18:29 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +            a.[i] <- fibTailRec i
Круууть) А можно как-то более оптимально это сделать?

2020-10-03 18:29 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW3.fs
> +            if abs n < 10 then Expect.equal (fibRec (abs n)) (fibIt (abs n)) "Results for fibRec and fibIt should be equal"  // fibRec can't handle large n due to the stack overflowing
А почему на бОльших n не эквивалентны? И почему остальные реализации эквивалентны?

2020-10-04 18:54 UTC, kirillgarbar commented on tests/FirstSem.Tests/TestsHW3.fs
> +            if abs n < 10 then Expect.equal (fibRec (abs n)) (fibIt (abs n)) "Results for fibRec and fibIt should be equal"  // fibRec can't handle large n due to the stack overflowing
Из-за большого n в первой функции стек вызовов забивает всю память и программа выполняется бесконечно долго, поэтому ограничил передаваемый n.

2020-10-04 18:54 UTC, kirillgarbar commented on src/FirstSem/HW3.fs
> +        for i = 2 to p do
Возведение в отрицательную степень реализовывать не нужно?

2020-10-04 19:00 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +        for i = 2 to p do
В отрицательную не нужно) А нулевую Вы просто потеряли где-то, дело дае не в реализации её.

2020-10-04 19:02 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW3.fs
> +            if abs n < 10 then Expect.equal (fibRec (abs n)) (fibIt (abs n)) "Results for fibRec and fibIt should be equal"  // fibRec can't handle large n due to the stack overflowing
При 10. Весь стек. Гм.... Странно мне всё это. Не, ну может, конечно.

2020-10-04 19:07 UTC, kirillgarbar commented on src/FirstSem/HW3.fs
> +        let rec go n =
Не понимаю что именно тут сложно, по-другому эту строку сделать?
![image](https://user-images.githubusercontent.com/71129570/95024759-e52cb580-068d-11eb-85d8-d1a6ea31126b.png)

2020-10-04 19:27 UTC, kirillgarbar commented on tests/FirstSem.Tests/TestsHW3.fs
> +            if abs n < 10 then Expect.equal (fibRec (abs n)) (fibIt (abs n)) "Results for fibRec and fibIt should be equal"  // fibRec can't handle large n due to the stack overflowing
До 50 работает, дальше намертво висит

2020-10-05 13:59 UTC, gsvgit commented
Ну ладно, бывает. Но не 10 же.
Regards,
Semyon Grigorev.


вс, 4 окт. 2020 г. в 22:27, kirillgarbar <notifications@github.com>:

> *@kirillgarbar* commented on this pull request.
> ------------------------------
>
> In tests/FirstSem.Tests/TestsHW3.fs
> <https://github.com/kirillgarbar/FirstSem/pull/6#discussion_r499280162>:
>
> > +
>
> +        testCase "Task 4.1 Negative number given" <| fun _ ->
>
> +            Expect.throws (fun _ -> naiveFibMatrix -1 |> ignore) "Exception should be raised"
>
> +
>
> +        testCase "Task 5.1 Negative number given" <| fun _ ->
>
> +            Expect.throws (fun _ -> logFibMatrix -1 |> ignore) "Exception should be raised"
>
> +
>
> +        testCase "Task 6.1 Negative number given" <| fun _ ->
>
> +            Expect.throws (fun _ -> allFib -1 |> ignore) "Exception should be raised"
>
> +        testCase "Task 6.2 Common case" <| fun _ ->
>
> +            Expect.sequenceEqual (allFib 5) ([| 1; 1; 2; 3; 5; 8 |]) "All fib numbers from 0 to 5 =/= 1; 1; 2; 3; 5; 8?"
>
> +        testProperty "Task 6.3 At least last fib number in sequence is correct" <| fun (n:int) ->
>
> +            if n <> 0 then Expect.equal (allFib (abs n)).[abs(n)] (logFibMatrix (abs n)) "Last number in sequence is wrong"  // len of array if n = 0 equals 1, so .[n] is out of bounds
>
> +
>
> +        testProperty "Task 1 and 2" <| fun (n:int) ->
>
> +            if abs n < 10 then Expect.equal (fibRec (abs n)) (fibIt (abs n)) "Results for fibRec and fibIt should be equal"  // fibRec can't handle large n due to the stack overflowing
>
>
> До 50 работает, дальше намертво висит
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/kirillgarbar/FirstSem/pull/6#discussion_r499280162>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQBOL5HNSZQZ3I3I7N3SJDEDBANCNFSM4SCC5DAQ>
> .
>

2020-10-08 14:36 UTC, kirillgarbar commented on src/FirstSem/HW3.fs
> +        let rec go n =
Вы не пропустили этот вопрос?

2020-10-15 07:47 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +        let rec go n =
Извините, пропустил. 1) Кажется, матрицу, которую Вы используете для вычисления, проще как-то назвать коротко, а не каждый раз писать как каонстанту на месте. Вероятно, это уже сделает код компактнее и читабельнее. Я не про сложность в смысле алгоритма, а про то, что написано как-то так, что читать сложно.

2020-10-15 09:09 UTC, kirillgarbar commented
В функции powMat считаю нужным оставить проверку на квадратность передаваемой матрицы, так как в случае возведения  матрицы в нулевую степень она тоже должна быть квадратной

2020-10-15 09:24 UTC, gsvgit commented
Вообще говоря, в степень впринципе можно спокойно возводить только
квадратные матрицы. Если у Вас получится умножить прямоугольную (но не
квадратную) матрицу саму на себя, обязательно расскажите, как Вам это
удалось.

Regards,
Semyon Grigorev.


чт, 15 окт. 2020 г. в 12:09, kirillgarbar <notifications@github.com>:

> В функции powMat считаю нужным оставить проверку на квадратность
> передаваемой матрицы, так как в случае возведения матрицы в нулевую степень
> она тоже должна быть квадратной
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/kirillgarbar/FirstSem/pull/6#issuecomment-709021784>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQCRBOEZOWCH42JXOVDSK234DANCNFSM4SCC5DAQ>
> .
>

2020-10-15 09:39 UTC, kirillgarbar commented
Я это к тому, что функция умножения матриц сама проверит, что матрица квадратная, так что если бы не случай с нулевой степенью, эту проверку в функции powMat можно было бы убрать
![image](https://user-images.githubusercontent.com/71129570/96106059-692f3a80-0ee3-11eb-911e-90f1300c5a9c.png)

2020-10-22 08:50 UTC, gsvgit requested changes

2020-10-22 08:50 UTC, gsvgit commented on src/FirstSem/HW3.fs
> +        if n = 0
Что-то Вы переусложняете. 
1) В массиве уже накапливаются предыдущие значения.
2) Кажется, инициализацию результирующего массива можно унифицировать. Не надо на разные варианты разносить.

2020-10-22 08:50 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW3.fs
> +            Expect.sequenceEqual (powMat ([| [| 0; 1 |]; [| 1; 1 |] |]) 0) [| [| 1; 0 |]; [| 0; 1 |] |] "[| 1; 0 |]; [| 0; 1 |] was waited"
А какие-то другие матрицы умеем в степень возводить?

2020-10-22 08:50 UTC, gsvgit commented on tests/FirstSem.Tests/TestsHW3.fs
> +        testCase "Build identity matrix test. Common case" <| fun _ ->
Ну и про умножение тоже интересно. Можем ли мы что-то коме матриц для чисел Фибоначчи умножать.

2020-10-26 10:05 UTC, gsvgit approved these changes
Ok

2020-10-26 10:29 UTC, merged