HW4 is done
kirillgarbar/FirstSem pull request #7
Opened 2020-10-28 14:42 UTC by kirillgarbar

Выполнил все задания

2020-11-03 06:42 UTC, gsvgit commented
И как, мне уже пора проверять или Вы ещё чего сейчас накоммитите?

2020-11-03 07:54 UTC, kirillgarbar commented
> И как, мне уже пора проверять или Вы ещё чего сейчас накоммитите?

Когда начал делать следующее дз, нашёл проблемы в этой и, учитывая, что работа долго не проверялась, не стеснялся делать коммиты. Больше ничего коммитить не буду)

2020-11-06 19:35 UTC, gsvgit requested changes

2020-11-06 19:35 UTC, gsvgit commented on src/HW4/HW4.fs
> +let rec arrayQuickSort (a:array<int>) =
Оставляем эту сортировку для замеров проиводительности и пишем ещ1 один вариант, который не так агрессивно использует память.

2020-11-06 19:35 UTC, gsvgit commented on src/HW4/HW4.fs
> +        (listQuickSort left) @ [pivot] @ (listQuickSort right)
А зачем создавать список из одного элемента.

2020-11-06 19:35 UTC, gsvgit commented on src/HW4/HW4.fs
> +    let ab = unpack32To16 (fst abcd)
Можно написать ```let a, b = unpack...``` И тогда не надо fst, snd использовать.

2020-11-07 14:32 UTC, kirillgarbar commented on src/HW4/HW4.fs
> +let rec arrayQuickSort (a:array<int>) =
![image](https://user-images.githubusercontent.com/71129570/98443757-8a6bfb00-211e-11eb-9773-ded72258159d.png)
![image](https://user-images.githubusercontent.com/71129570/98443767-a40d4280-211e-11eb-8e12-afd7f4575485.png)
Когда писал такую сортировку, наткнулся на то, что если не делать копию массива перед сортировкой, то меняется какой-то уже существующий массив(как когда мы писали свой Array.map на паре), но не требуется выделять совершенно никакой памяти под новый массив. Однако, учитывая, что остальные написанные сортировки возвращают именно новый массив, не трогая старый, считаю необходимым делать копию массива(как на первом скрине) и сортировать уже её. Какой из вариантов оставить?

2020-11-07 16:55 UTC, gsvgit commented on src/HW4/HW4.fs
> +let rec arrayQuickSort (a:array<int>) =
Хороший вопрос. Как мы видели на паре, в стандартной библиотеке даже специально разделены sort и sortInPlace. Так что оба варианта имеют права на существование. Разве что ради единообразия можете оставить тот, в котором создаётся копия.

2020-11-07 17:21 UTC, gsvgit approved these changes
В целом нормально. Хотя по оформлению мелочей ещё дофига.

2020-11-07 17:21 UTC, gsvgit commented on src/HW4/HW4.fs
> +        (a |> int32 <<< 16) + (b |> int32)
А зачем во второй скобке пайп?

2020-11-07 17:21 UTC, gsvgit commented on src/HW4/HW4.fs
> +let pack16To32 (a:int16,b:int16) =
Пробел потерян.

2020-11-07 19:22 UTC, merged